import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Created using Next.js{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Clean Code</h2>
            <Image src= "/imgs/clean_code.jpg" width={100} height={150}></Image>
            <h3>Escrito por Uncle Bob</h3>
            <sub>Resumo de Rodrigo Martins</sub>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Clean Archtecture</h2>
            <Image src= "/imgs/archtecture.jpeg" width={100} height={150}></Image>
            <h3>Escrito por Uncle Bob</h3>
            <sub>Resumo de Rodrigo Martins</sub>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Design Patterns </h2>
            <Image src= "/imgs/patterns.jpg" width={100} height={150}></Image>
            <h3>Escrito por Uncle Bob</h3>
            <sub>Resumo de Rodrigo Martins</sub>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Grokking Algo</h2>
            <Image src= "/imgs/groking.jpg" width={100} height={150}></Image>
            <h3>Escrito por Uncle Bob</h3>
            <sub>Resumo de Rodrigo Martins</sub>
          </a>
        </div>
      </main>
    </div>
  )
}
