import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useRef, useEffect, useState } from 'react';
import axios from 'axios';
import Card from '../components/card';


export default function Home() {
  const [books, setBooks] = useState([]);
  const shouldGetBooks = useRef(true)

  useEffect(() => {
    if (shouldGetBooks.current) {
      shouldGetBooks.current = false

    axios.get('http://localhost:3000/api/books').then(response => {
      console.log(response.data);
      setBooks(response.data);
    })
  }
    
  }, []);


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Books Summary 
        </h1>
        <div className={styles.grid}>
          {books.map((book, i)=> 
            <Card book ={book} key={i}/>
          )}
        </div>
      </main>
    </div>
  )
}
