
import axios from 'axios';
import Head from 'next/head';
import { useRouter } from 'next/router'
import { useEffect, useState  }from 'react';
import styles from'../../styles/Home.module.css'

function books(books) {
  const [book, setBook] = useState({});
  const router = useRouter()
  const { id } = router.query

  useEffect(() => {
    if(!id) {
        return;
      }
      
    axios.get(`http://localhost:3000/api/books/${id}`).then(response => {
      console.log(response.data);
      setBook(response.data);
    })

  }, [id]);
   
  return ( 
    <div className={styles.container}>
      <Head>
        <title>{book.title} - Summary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        {book.title} 
        </h1>
        <div className={styles.grid}>
        </div>
      </main>
    </div>);
}

export default books;