
import axios from 'axios';
import Head from 'next/head';
import { useRouter } from 'next/router'
import { useEffect, useState  }from 'react';
import styles from'../../styles/Home.module.css'
import {BookInfo} from '../../components';

function Books() {
  const [book, setBook] = useState(null);
  const router = useRouter()
  const { id } = router.query

  useEffect(() => {
    if(!id) {
        return;
      }
      
    axios.get(`http://localhost:3000/api/books/${id}`).then(response => {
      console.log(response.data);
      setBook(response.data);
    })

  }, [id]);
   
  return !!book && ( 
    <div className={styles.container}>
      <Head>
        <title>{book.title} - Summary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        {book.title} 
        </h1>
        <div style={{ maxWidth: 900, width: '100%',textAlign: 'justify', whiteSpace: 'break-spaces', lineHeight: '1.8em'}}>
          <p>{book.summary}</p>
        </div>
        <BookInfo book={book}/>
      </main>
    </div>);
}

export default Books;